-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 12:17:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `spotify` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `spotify` ;

-- Table `spotify`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`album` ;

CREATE TABLE IF NOT EXISTS `spotify`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `year_of_publication` DATE NULL DEFAULT NULL,
  `cover` BLOB NULL DEFAULT NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `artist_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `artist`
    FOREIGN KEY (`artist_id`)
    REFERENCES `spotify`.`artist` (`id_artist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`artist` ;

CREATE TABLE IF NOT EXISTS `spotify`.`artist` (
  `id_artist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_artist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`creditcard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`creditcard` ;

CREATE TABLE IF NOT EXISTS `spotify`.`creditcard` (
  `id_creditcard` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `CVV` INT NOT NULL,
  `subscription_id` INT NOT NULL,
  PRIMARY KEY (`id_creditcard`),
  INDEX `creditcard_subs_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `creditcard_subs`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `spotify`.`premium_subscription` (`id_subscription`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`favourite_album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`favourite_album` ;

CREATE TABLE IF NOT EXISTS `spotify`.`favourite_album` (
  `favourite_album_id` INT NOT NULL,
  `album_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`favourite_album_id`),
  INDEX `album_liked_idx` (`album_id` ASC) VISIBLE,
  INDEX `user_likes_album_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `album_liked`
    FOREIGN KEY (`album_id`)
    REFERENCES `spotify`.`album` (`id_album`),
  CONSTRAINT `user_likes_album`
    FOREIGN KEY (`user_id`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`favourite_artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`favourite_artist` ;

CREATE TABLE IF NOT EXISTS `spotify`.`favourite_artist` (
  `favourite_artist_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`favourite_artist_id`),
  INDEX `artist_liked_idx` (`artist_id` ASC) VISIBLE,
  INDEX `user_likes_artist_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `artist_liked`
    FOREIGN KEY (`artist_id`)
    REFERENCES `spotify`.`artist` (`id_artist`),
  CONSTRAINT `user_likes_artist`
    FOREIGN KEY (`user_id`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`favourite_song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`favourite_song` ;

CREATE TABLE IF NOT EXISTS `spotify`.`favourite_song` (
  `favourite_song_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`favourite_song_id`),
  INDEX `song_liked_idx` (`song_id` ASC) VISIBLE,
  INDEX `user_likes_song_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `song_liked`
    FOREIGN KEY (`song_id`)
    REFERENCES `spotify`.`song` (`id_song`),
  CONSTRAINT `user_likes_song`
    FOREIGN KEY (`user_id`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`payment` ;

CREATE TABLE IF NOT EXISTS `spotify`.`payment` (
  `id_payment` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `invoice_num` INT NOT NULL,
  `total_price` FLOAT NOT NULL,
  `subscription_id` INT NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `payment_subs_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `payment_subs`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `spotify`.`premium_subscription` (`id_subscription`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`paypal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`paypal` ;

CREATE TABLE IF NOT EXISTS `spotify`.`paypal` (
  `id_paypal` INT NOT NULL AUTO_INCREMENT,
  `username_paypal` VARCHAR(45) NOT NULL,
  `subscription_id` INT NOT NULL,
  PRIMARY KEY (`id_paypal`),
  INDEX `paypal_subs_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `paypal_subs`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `spotify`.`premium_subscription` (`id_subscription`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`playlist` ;

CREATE TABLE IF NOT EXISTS `spotify`.`playlist` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `total_songs` INT NULL DEFAULT NULL,
  `creation_date` DATE NOT NULL,
  `deletion_date` DATE NULL DEFAULT NULL,
  `created_by_user_id` INT NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `user_creates_playlist_idx` (`created_by_user_id` ASC) VISIBLE,
  CONSTRAINT `user_creates_playlist`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`premium_subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`premium_subscription` ;

CREATE TABLE IF NOT EXISTS `spotify`.`premium_subscription` (
  `id_subscription` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `renovation_date` DATE NOT NULL,
  `payment_method` ENUM('creditcard', 'paypal') NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_subscription`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  CONSTRAINT `user_pays`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`song` ;

CREATE TABLE IF NOT EXISTS `spotify`.`song` (
  `id_song` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `length` VARCHAR(45) NULL DEFAULT NULL,
  `num_views` INT NULL DEFAULT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`id_song`),
  INDEX `album_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `album`
    FOREIGN KEY (`album_id`)
    REFERENCES `spotify`.`album` (`id_album`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`song_added`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`song_added` ;

CREATE TABLE IF NOT EXISTS `spotify`.`song_added` (
  `id_song_added` INT NOT NULL AUTO_INCREMENT,
  `addition_date` DATE NOT NULL,
  `user_adds_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  `playlist_id` INT NOT NULL,
  PRIMARY KEY (`id_song_added`),
  INDEX `user_adds_idx` (`user_adds_id` ASC) VISIBLE,
  INDEX `song_idx` (`song_id` ASC) VISIBLE,
  INDEX `playlist_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `playlist`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `spotify`.`playlist` (`id_playlist`),
  CONSTRAINT `song`
    FOREIGN KEY (`song_id`)
    REFERENCES `spotify`.`song` (`id_song`),
  CONSTRAINT `user_adds`
    FOREIGN KEY (`user_adds_id`)
    REFERENCES `spotify`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`user` ;

CREATE TABLE IF NOT EXISTS `spotify`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('free', 'premium') NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
